apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-webserver
  namespace: pfinal
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 1
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver-container
        image: opusidea/nuvolapp:5
        env:
        - name: MONGO_HOST
          value: "mongo"
        imagePullPolicy: Always # force le re-download (pull) de l'image même si déjà présente dans le cluster
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: pfinal
spec:
  type: NodePort # Exposition externe
  selector:
    app: webserver
  ports:
  - port: 4000 # port du service (proxy) pour traffic interne
    targetPort: 4000 # port des pods du déploiement
    nodePort: 31300 # port ouvert pour l'extérieur du cluster
    protocol: TCP
